- name: Bootstrap MacOS
  hosts: 127.0.0.1
  gather_facts: False

  tasks:
  - name: Install Brew Packages
    homebrew:
      name: '{{ brew_packages }}'
      state: present
    vars:
      brew_packages:
      - ack
      - bash-git-prompt
      - bat
      - cask
      - coreutils
      - dos2unix
      - findutils
      - git-delta
      - jq
      - pyenv
      - pyenv-virtualenv
      - shellcheck
      - tree
      - watch
      - wget

  tasks:
  - name: Install Brew Cask Packages
    homebrew_cask:
      name: '{{ cask_packages }}'
      state: present
      accept_external_apps: true
      update_homebrew: true
    vars:
      cask_packages:
      - alfred
      - docker
      - google-backup-and-sync
      - google-chrome
      - iina
      - iterm2
      - ivpn
      - slack
      - spotify
      - visual-studio-code
      - zoomus
